apiVersion: v1
kind: Service
metadata:
  name: nginx-test1
spec:
  type: NodePort
  selector:
    app: nginx-test1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30100
