apiVersion: v1
kind: Service
metadata:
  name: mongo-express-test-service
spec:
  selector:
    app: mongo-express-test
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30101
